### ISSUE TITLE
Remove Password requirements

### ISSUE THREAD

**Issue by Thane5** [trenta-io/trentaos-core#5]
since i was running Trenta in a VM, i wanted to use a very basic four-letter password. Apparently it would not let me do that, because it was too simple or using "common words". Restrictions like this should not exists, i also have not seen this on any other linux distro before.

**Comment by Thane5** [comment]
Okay i found that these restrictions do not exist if you boot directly into the installation mode, where it uses the more standard setup.

**Comment by agam778** [comment]
So please close the issue
