### ISSUE TITLE
[Feature Suggestion] Use the POP! Shop as the default app store

### ISSUE THREAD

**Issue by Thane5** [trenta-io/trentaos-core#6]
Currently the OS uses the default Ubuntu Software Center. However there is a more fitting option out there, the POP! Shop: https://github.com/pop-os/shop
It is based on the Elementary OS App center, which again tries to offer a more MacOS-like experience.

**Comment by agam778** [comment]
I totally disgaree with this as POP!_OS Shop aka Elementary OS App Center does not have many apps just like GNOME Software and does not have good support for Snap and Flatpak. And Elementary OS App Center does not look that much like MacOS App Store. I would recommend to keep GNOME Software Only.

**Comment by johncaling40** [comment]
I think that the GNOME Software is better for the large catalog.
